version: '3'
services:
  jenkins:
    build: .
    #image: jenkins/jenkins:lts
    ports:
      - 8089:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #  - /usr/bin/docker:/usr/bin/docker
    restart: always